name: review
description: "Run workflow dispatch"
inputs:
  head-ref:
    required: true
    description: "github head-ref"
  github-token:
    required: true
  workflow-yml:
    required: true
    description: "workflow yaml name"
outputs:
  conclusion:
    description: "workflow result status"
    value: ${{steps.review.outputs.conclusion}}

permission:
  content: read
  pull-request: read
runs:
  using: composite
  steps:
    - name: echo input data
      shell: bash
      run: |
        echo ${{inputs.head-ref}}
        echo ${{inputs.workflow-yml}}
    - uses: actions/checkout@v4
      with:
        ref: ${{inputs.ref}}
    - name: run review
      env:
        GITHUB_TOKEN: ${{inputs.github-token}}
      shell: bash
      id: review
      run: |
        gh workflow run ${{inputs.workflow-yml}} --ref ${{inputs.head-ref}}
        sleep 3
        RUN_ID=$(gh run list --workflow=${{inputs.workflow-yml}} -b ${{inputs.head-ref}} -e workflow_dispatch --json number,status,conclusion,databaseId --jq '. | max_by(.number).databaseId')
        gh run watch ${RUN_ID}
        conclusion=$(gh run list --workflow=${{inputs.workflow-yml}} -b ${{inputs.head-ref}} -e workflow_dispatch --json number,status,conclusion,databaseId --jq ".[] | select(.databaseId == ${RUN_ID}).conclusion")
        echo "conclusion=${conclusion}"
        echo "conclusion=${conclusion}" >> "$GITHUB_OUTPUT"
