name: sample
description: this is sample
inputs:
  tag:
    required: true
    description: tag
    default: ''
  token:
    required: true
    description: GitHub Token
  ref:
    required: true
    description: git ref
    default: 'staging'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{inputs.ref}}
    - name: git tag push
      run: |
        git tag ${{inputs.tag}}
        git push --tags -f origin ${{inputs.tag}}
      shell: bash
