name: sample
description: this is sample
inputs:
  tag:
    required: true
    description: tag
    default: ''
  token:
    required: true
    description: GitHub Token
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: git tag push
      run: |
        git tag ${{inputs.tag}}
        git push origin ${{inputs.tag}}
      shell: bash
