name: mysql
description: run mysql
inputs:
  git-ref:
    required: true
    description: "Git Ref"

runs:
  using: composite
  steps:
    - name: Start MySQL
      shell: bash
      run: |
        docker run -d --name mysql \
          -p 3306:3306 \
          -e MYSQL_ROOT_PASSWORD=rootpassword \
          -e MYSQL_DATABASE=mydatabase \
          -e MYSQL_USER=myuser \
          -e MYSQL_PASSWORD=mypassword \
          --health-cmd="mysqladmin ping" \
          --health-interval="5s" \
          --health-timeout="5s" \
          --health-retries="5" \
          mysql:8.0.37
    - name: Test
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        mysql -h 127.0.0.1 -umyuser -prootpassword mydatabase -e 'show databases'
