name: mysql
description: run mysql
inputs:
  git-ref:
    required: true
    description: "Git Ref"

runs:
  using: composite
  steps:
    - name: Start MySQL
      uses: docker://mysql:8.0.37
      with:
        ports: 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
