# see: https://docs.github.com/ja/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status
name: update-status
description: "Update GitHub pull request status"
inputs:
  github-token:
    required: true
  repository:
    required: true
  commit-sha:
    required: true
    description: "Commit SHA(long version)"
  state:
    required: true
    description: "Update state"
  context:
    required: true
    description: "context"
permission:
  content: read
  pull-request: read
runs:
  using: composite
  steps:
    - name: update status
      shell: bash
      env:
        GITHUB_TOKEN: ${{inputs.github-token}}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{inputs.repository}}/statuses/${{inputs.commit-sha}} \
         -f "state=${{inputs.state}}" -f "context=${{inputs.context}}"
