# developブランチにマージするとmasterブランチへのPRを作るワークフロー
# see https://github.com/x-motemen/git-pr-release
name: git-pr-release
on:
  push:
    branches:
      - development
      - staging
jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          ruby-version: '3.3'
        # git-pr-releaseを使うためにGemfileを少し借りる
      - name: Bundle install
        run: |
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git-pr-release needs the git histories
      - name: Install git-pr-release
        run: |
          gem install specific_install
          gem specific_install -l https://github.com/hachi-eiji/git-pr-release.git -b 'feat/add-draft-option'
      - name: Create pull request from development to staging
        if: ${{ github.refs == 'refs/heads/development' }}
        run: |
          git-pr-release --squashed
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: staging
          GIT_PR_RELEASE_BRANCH_STAGING: development
          GIT_PR_RELEASE_LABELS: pr-release
          GIT_PR_RELEASE_DRAFT: true
          TZ: Asia/Tokyo
      - name: Create pull request from staging to main
        if: ${{ github.refs == 'refs/heads/staging' }}
        run: |
          git-pr-release --squashed
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: staging
          GIT_PR_RELEASE_LABELS: pr-release
          GIT_PR_RELEASE_DRAFT: true
          TZ: Asia/Tokyo
