name: tag.yml
on:
  repository_dispatch:
    types: [on-demand-test]
  push:
    branches:
      - staging
permissions:
  contents: write
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: ./.github/actions/tag/staging
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         tag: 'staging-test'
