name: tag.yml
on:
  push:
    branches:
      - staging
  workflow_call:
permissions:
  contents: write
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tag/staging
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'staging-test'
