name: tag.yml
on:
  workflow_call:
  push:
    branches:
      - staging
permissions:
  contents: write
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: 'hachi-eiji/sandbox-tag-parent'
      - uses: ./.github/actions/tag/staging
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'staging-test'
