name: test
on:
  workflow_call:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cat
        shell: bash
        run: |
          cat ./.github/test.md
