name: test
on:
  workflow_call:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v4
      - name: update git commit
        shell: bash
        run: echo 'hello'
