name: update pull request
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    outputs:
      sha: ${{steps.commit.outputs.sha}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: update git commit
        shell: bash
        id: commit
        run: |
          echo "test\n" >> .github/test.md
          git add .github/test.md
          git config --local user.name "Eiji Hachiya"
          git config --local user.email "hachiyae@gmail.com"
          git remote set-url origin "https://${GITHUB_AUTHOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git commit -m "chore: update"
          git push -u origin HEAD:${{github.event.pull_request.head.ref}}
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
  re-run-review1:
    runs-on: ubuntu-latest
    needs: [update-commit]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    outputs:
      conclusion: ${{ steps.review.outputs.conclusion }}
    steps:
      - uses: actions/checkout@v4
      - name: re-run review
        shell: bash
        id: review
        run: |
          gh workflow run test.yml --ref ${{github.head_ref}}
          RUN_ID=$(gh run list --workflow=test.yml -b ${{github.head_ref}} -e workflow_dispatch --json number,status,conclusion,databaseId --jq '. | max_by(.number).databaseId')
          gh run watch ${RUN_ID}
          conclusion=$(gh run list --workflow=test2.yml -b test-hoge -e workflow_dispatch --json number,status,conclusion,databaseId --jq '. | select_by(.databaseId =="$RUN_ID").conclusion')
          echo "conclusion=${conclusion}" >> "$GITHUB_OUTPUT"
  re-run-review2:
    runs-on: ubuntu-latest
    needs: [update-commit]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    outputs:
      conclusion: ${{ steps.review2.outputs.conclusion }}
    steps:
      - uses: actions/checkout@v4
      - name: re-run review2
        shell: bash
        id: review2
        run: |
          gh workflow run test2.yml --ref ${{github.head_ref}}
          RUN_ID=$(gh run list --workflow=test2.yml -b ${{github.head_ref}} -e workflow_dispatch --json number,status,conclusion,databaseId --jq '. | max_by(.number).databaseId')          
          gh run watch $RUN_ID
          conclusion=$(gh run list --workflow=test2.yml -b test-hoge -e workflow_dispatch --json number,status,conclusion,databaseId --jq '. | select_by(.databaseId =="$RUN_ID").conclusion')
          echo "conclusion=${conclusion}" >> "$GITHUB_OUTPUT"
  update-status-review1:  
    runs-on: ubuntu-latest
    needs: [re-run-review1]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: update status
        shell: bash
        run: |
          STATUS=${{needs.re-run-review1.outputs.conclusion}}
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"state": "${STATUS}", "context": "review2", "description": "Description of the status"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ needs.update-commit.outputs.sha }}
  update-status-review2:
    runs-on: ubuntu-latest
    needs: [re-run-review2]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: update status
        shell: bash
        run: |
          STATUS=${{needs.re-run-review2.outputs.conclusion}}
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"state": "${STATUS}", "context": "review2", "description": "Description of the status"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ needs.update-commit.outputs.sha }}
