name: update pull request
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
    outputs:
      sha: ${{steps.commit.outputs.sha}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: update git commit
        shell: bash
        id: commit
        run: |
          echo "test\n" >> .github/test.md
          git add .github/test.md
          git config --local user.name "dependabot[bot]"
          git config --local user.email "dependabot[bot]@users.noreply.github.com"
          git remote set-url origin "https://${GITHUB_AUTHOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git commit -m "chore: update"
          git push -u origin HEAD:${{github.event.pull_request.head.ref}}
          git rev-parse HEAD
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
  re-run-review1:
   runs-on: ubuntu-latest
   needs: [update-commit]   
   outputs:
     conclusion: ${{ steps.review.outputs.conclusion }}
     sha: ${{needs.update-commit.outputs.sha}}
   steps:
     - uses: actions/checkout@v4
     - name: review
       id: review
       uses: ./.github/actions/review
       with:
         head-ref: ${{github.head_ref}}
         github-token: ${{ secrets.PAT }}
         workflow-yml: test2.yml
  re-run-review2:
    runs-on: ubuntu-latest
    needs: [update-commit]
    outputs:
      conclusion: ${{ steps.review.outputs.conclusion }}
      sha: ${{needs.update-commit.outputs.sha}}
    steps:
      - uses: actions/checkout@v4
      - name: review
        id: review
        uses: ./.github/actions/review
        with:
          head-ref: ${{github.head_ref}}
          github-token: ${{ secrets.PAT }}
          workflow-yml: test2.yml
  update-status-review1:
    runs-on: ubuntu-latest
    needs: [re-run-review1]
    steps:
      - uses: actions/checkout@v4
      - name: update status
        uses: ./.github/actions/update-status
        with:
          github-token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          commit-sha: ${{ needs.re-run-review1.outputs.sha }}
          state: ${{ needs.re-run-review1.outputs.conclusion }}
          context: review
  update-status-review2:
    runs-on: ubuntu-latest
    needs: [re-run-review2]
    steps:
      - uses: actions/checkout@v4
      - name: update status
        uses: ./.github/actions/update-status
        with:
          github-token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          commit-sha: ${{ needs.re-run-review2.outputs.sha }}
          state: ${{ needs.re-run-review2.outputs.conclusion }}
          context: review2
