name: update pull request
on:
  pull_request:
     types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: update git commit
        shell: bash
        id: commit
        run: |
          echo "test\n" >> .github/test.md
          git add .github/test.md
          git config --local user.name "Eiji Hachiya"
          git config --local user.email "hachiyae@gmail.com"
          git remote set-url origin "https://${GITHUB_AUTHOR}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}.git"
          git commit -m "chore: update"
          git push -u origin HEAD:${{github.event.pull_request.head.ref}}
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - name: update status
        shell: bash
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_PAT}" \
            -d '{"state": "success", "context": "review", "description": "Description of the status"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.commit.outputs.sha }}
          curl -X POST -H "Authorization: token ${GITHUB_PAT}" \
            -d '{"state": "success", "context": "review2", "description": "Description of the status"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.commit.outputs.sha }}
