name: update pull request
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: update git commit
        shell: bash
        id: commit
        run: |
          echo "test\n" >> .github/test.md
          git add .github/test.md
          git config --local user.name "Eiji Hachiya"
          git config --local user.email "hachiyae@gmail.com"
          git remote set-url origin "https://${GITHUB_AUTHOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git commit -m "chore: update"
          git push -u origin HEAD:${{github.event.pull_request.head.ref}}
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
  re-run-review:
    runs-on: ubuntu-latest
    needs: [update-commit]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: re-run review
        shell: bash
        id: review
        continue-on-error: true
        run: |
          gh workflow run test.yml --ref ${{github.head_ref}}
      - name: re-run review2
        shell: bash
        id: review2
        continue-on-error: true
        run: |
          gh workflow run test2.yml --ref ${{github.head_ref}}   
  update-status:  
    runs-on: ubuntu-latest
    needs: [re-run-review]
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: update status
        shell: bash
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"state": "${{steps.review.conclusion}}", "context": "review", "description": "Description of the status"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.commit.outputs.sha }}
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"state": "${{steps.review2.conclusion}}", "context": "review2", "description": "Description of the status"}' \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.commit.outputs.sha }}
